spring.application.name=social-media-slop
spring.ai.openai.api-key: ${OPENAI_API_KEY}
server.port=8099
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.client.observations.log-completion=true
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.config.import=classpath:custom.properties