#spring.ai.mcp.client.streamable-http.connections.tweets.url=http://localhost:8085

spring.ai.mcp.client.sse.connections.my-toolkit.url=http://localhost:8085
spring.ai.mcp.client.sse.connections.my-toolkit.sse-endpoint=/sse
spring.main.headless=false