spring.application.name=mcppppp

# Keep it simple for a tutorial
#spring.ai.mcp.server.type=SYNC
#spring.ai.mcp.server.protocol=STREAMABLE
#spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp

server.port=8085